### PR TITLE
Minor changes to exam04 and exam05

### PR DESCRIPTION
**Pull request by Antoine-lb**

### CODE REVIEW

**Review by markveligod — COMMENTED** [review]
So here you were confused by the very name of the function? :D

**Comment by Antoine-lb** [comment]
A bit, because a leak is lost memory, meaning that you lost the address of that allocation. So when I saw it I was like: how the f**k did russians manadge to recover lost memory o.O, to then realize is simply freeing the memory

**Comment by markveligod** [comment]
with exam 5, really classes are not copyable. Thank you for your help!

**Comment by Antoine-lb** [comment]
Thank you for your help, I got exam 04 and 05 using this repo, really helpfull

**Pull request merged**
